# Preprocess 예제 1 : Getting & Knowing Data

In [202]:
import pandas as pd

# 데이터 로드
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/lol.csv', sep='\t')

In [203]:
# 데이터 상위 5개 행 출력
df.head()

,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,t2_towerKills,t2_inhibitorKills,t2_baronKills,t2_dragonKills,t2_riftHeraldKills,t2_ban1,t2_ban2,t2_ban3,t2_ban4,t2_ban5
0,3326086514,1504279457970,1949,9,1,2,1,1,1,1,...,5,0,0,1,1,114,67,43,16,51
1,3229566029,1497848803862,1851,9,1,1,1,1,0,1,...,2,0,0,0,0,11,67,238,51,420
2,3327363504,1504360103310,1493,9,1,2,1,1,1,2,...,2,0,0,1,0,157,238,121,57,28
3,3326856598,1504348503996,1758,9,1,1,1,1,1,1,...,0,0,0,0,0,164,18,141,40,51
4,3330080762,1504554410899,2094,9,1,2,1,1,1,1,...,3,0,0,1,0,86,11,201,122,18

In [204]:
# 데이터의 행과 열의 갯수 출력
print(df.shape)
print(df.shape[0])
print(df.shape[1])

(51490, 61)
51490
61

In [205]:
# 전체 컬럼 출력
df.columns

Index(['gameId', 'creationTime', 'gameDuration', 'seasonId', 'winner',
       'firstBlood', 'firstTower', 'firstInhibitor', 'firstBaron',
       'firstDragon', 'firstRiftHerald', 't1_champ1id', 't1_champ1_sum1',
       't1_champ1_sum2', 't1_champ2id', 't1_champ2_sum1', 't1_champ2_sum2',
       't1_champ3id', 't1_champ3_sum1', 't1_champ3_sum2', 't1_champ4id',
       't1_champ4_sum1', 't1_champ4_sum2', 't1_champ5id', 't1_champ5_sum1',
       't1_champ5_sum2', 't1_towerKills', 't1_inhibitorKills', 't1_baronKills',
       't1_dragonKills', 't1_riftHeraldKills', 't1_ban1', 't1_ban2', 't1_ban3',
       't1_ban4', 't1_ban5', 't2_champ1id', 't2_champ1_sum1', 't2_champ1_sum2',
       't2_champ2id', 't2_champ2_sum1', 't2_champ2_sum2', 't2_champ3id',
       't2_champ3_sum1', 't2_champ3_sum2', 't2_champ4id', 't2_champ4_sum1',
       't2_champ4_sum2', 't2_champ5id', 't2_champ5_sum1', 't2_champ5_sum2',
       't2_towerKills', 't2_inhibitorKills', 't2_baronKills', 't2_dragonKills',
       't2_riftHeraldKills', 't2_ban1', 't2_ban2', 't2_ban3', 't2_ban4',
       't2_ban5'],
      dtype='object')

In [206]:
# 6번째 컬럼명 출력
df.columns[5]

'firstBlood'

In [207]:
# 6번째 컬럼의 데이터 타입 확인
df.iloc[:,5].dtypes

dtype('int64')

In [208]:
# 데이터셋의 인덱스 구성
df.index

RangeIndex(start=0, stop=51490, step=1)

In [209]:
# 6번째 컬럼의 3번째 값
df.iloc[2,5]

np.int64(2)

In [210]:
# 데이터 불러오기
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/Jeju.csv', encoding='cp949')
df

,id,일자,시도명,읍면동명,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
0,22448,2018-01-01,제주시,도두동,32249.987,3418.266,102709.092,138377.345,39.556,29.167,5.0,0.0,2.50
1,22449,2018-01-01,제주시,외도동,213500.997,10341.172,112692.789,336534.958,32.900,30.900,5.0,0.0,2.50
2,22450,2018-01-01,제주시,이도2동,1212382.218,96920.834,541194.481,1850497.533,29.538,35.692,2.9,0.0,2.40
3,22451,2018-01-01,제주시,일도1동,33991.653,6034.253,72155.919,112181.825,30.000,23.500,2.9,0.0,2.40
4,22452,2018-01-01,서귀포시,대천동,155036.925,9403.969,150882.409,315323.303,41.583,14.375,5.1,0.0,2.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9616,32064,2020-04-30,서귀포시,표선면,228260.005,16891.732,152832.449,397984.186,44.514,34.054,18.1,0.0,4.70
9617,32065,2020-04-30,제주시,한림읍,459959.064,26007.122,249700.419,735666.605,48.609,61.377,18.0,0.0,4.35
9618,32066,2020-04-30,제주시,도두동,28397.481,3144.895,84052.697,115595.073,41.053,29.421,20.3,0.0,3.00
9619,32067,2020-04-30,서귀포시,안덕면,348037.846,29106.286,251129.660,628273.792,46.595,49.189,17.6,0.0,3.50
9620,32068,2020-04-30,제주시,연동,1010643.372,65673.477,447622.068,1523938.917,40.863,27.765,14.1,0.0,4.80

In [211]:
# 데이터 마지막 3개 행
df.tail(3)

,id,일자,시도명,읍면동명,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
9618,32066,2020-04-30,제주시,도두동,28397.481,3144.895,84052.697,115595.073,41.053,29.421,20.3,0.0,3.0
9619,32067,2020-04-30,서귀포시,안덕면,348037.846,29106.286,251129.660,628273.792,46.595,49.189,17.6,0.0,3.5
9620,32068,2020-04-30,제주시,연동,1010643.372,65673.477,447622.068,1523938.917,40.863,27.765,14.1,0.0,4.8

In [212]:
# 수치형 변수를 가진 컬럼만 출력
df.select_dtypes(exclude='object').columns

Index(['id', '거주인구', '근무인구', '방문인구', '총 유동인구', '평균 속도', '평균 소요 시간', '평균 기온',
       '일강수량', '평균 풍속'],
      dtype='object')

In [213]:
# 범주형 변수를 가진 컬럼만 출력
df.select_dtypes(include='object').columns

Index(['일자', '시도명', '읍면동명'], dtype='object')

In [214]:
# 각 컬럼의 결측키 숫자
df.isna().sum()

id          0
일자          0
시도명         0
읍면동명        0
거주인구        0
근무인구        0
방문인구        0
총 유동인구      0
평균 속도       0
평균 소요 시간    0
평균 기온       0
일강수량        0
평균 풍속       0
dtype: int64

In [215]:
# 각 컬럼의 데이터수, 데이터 타입
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9621 entries, 0 to 9620
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        9621 non-null   int64
 1   일자        9621 non-null   object
 2   시도명       9621 non-null   object
 3   읍면동명      9621 non-null   object
 4   거주인구      9621 non-null   float64
 5   근무인구      9621 non-null   float64
 6   방문인구      9621 non-null   float64
 7   총 유동인구    9621 non-null   float64
 8   평균 속도     9621 non-null   float64
 9   평균 소요 시간  9621 non-null   float64
 10  평균 기온     9621 non-null   float64
 11  일강수량      9621 non-null   float64
 12  평균 풍속     9621 non-null   float64
dtypes: float64(9), int64(1), object(3)
memory usage: 977.3+ KB

In [216]:
# 각 수치형 변수의 분포(사분위, 평균, 표준편차, 최대, 최소) 확인
df.describe()

,id,거주인구,근무인구,방문인구,총 유동인구,평균 속도,평균 소요 시간,평균 기온,일강수량,평균 풍속
count,9621.000000,9.621000e+03,9621.000000,9621.000000,9.621000e+03,9621.000000,9621.000000,9621.000000,9621.000000,9621.000000
mean,27258.000000,3.174315e+05,35471.201510,195889.561802,5.487922e+05,41.109084,37.215873,13.550828,6.972426,2.753171
std,2777.487804,2.982079e+05,40381.214775,140706.090325,4.608802e+05,8.758631,12.993786,7.745515,27.617260,1.498538
min,22448.000000,9.305552e+03,1407.936000,11538.322000,2.225181e+04,24.333000,12.667000,-9.600000,0.000000,0.000000
25%,24853.000000,9.539939e+04,12074.498000,99632.153000,2.216910e+05,34.250000,27.889000,7.600000,0.000000,1.700000
50%,27258.000000,2.221105e+05,21960.928000,152805.335000,3.866935e+05,39.640000,34.500000,13.400000,0.000000,2.400000
75%,29663.000000,4.106671e+05,40192.032000,236325.109000,6.406918e+05,49.105000,46.176000,19.700000,1.500000,3.400000
max,32068.000000,1.364504e+06,263476.965000,723459.209000,2.066484e+06,103.000000,172.200000,30.400000,587.500000,13.333000

In [217]:
# 거주인구 컬럼의 값 출력
df['거주인구']

0         32249.987
1        213500.997
2       1212382.218
3         33991.653
4        155036.925
           ...
9616     228260.005
9617     459959.064
9618      28397.481
9619     348037.846
9620    1010643.372
Name: 거주인구, Length: 9621, dtype: float64

In [218]:
# 평균속도 컬럼의 4분위 범위 값을 구하여라
df['평균 속도'].quantile(0.75) - df['평균 속도'].quantile(0.25)

np.float64(14.854999999999997)

In [219]:
# 읍면동명 컬럼의 유니크 밸류
df['읍면동명'].unique()

array(['도두동', '외도동', '이도2동', '일도1동', '대천동', '서홍동', '한경면', '송산동', '조천읍',
       '일도2동', '영천동', '예래동', '대륜동', '삼도1동', '이호동', '건입동', '중앙동', '삼양동',
       '삼도2동', '이도1동', '남원읍', '대정읍', '정방동', '효돈동', '아라동', '한림읍', '구좌읍',
       '용담1동', '오라동', '화북동', '연동', '표선면', '중문동', '성산읍', '안덕면', '천지동',
       '노형동', '동홍동', '용담2동', '봉개동', '애월읍'], dtype=object)

In [220]:
# 읍면동명 컬럼의 유니크밸류 갯수
# len(df['읍면동명'].unique())
df['읍면동명'].nunique()

41

# Preprocess 예제 2 : Filtering & Sorting

In [221]:
# Data Road
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/chipo.csv')
df

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [222]:
df.loc[df['quantity']==3].head()

,order_id,quantity,item_name,choice_description,item_price
409,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
689,284,3,Canned Soft Drink,[Diet Coke],$3.75
818,338,3,Bottled Water,NaN,$3.27
850,350,3,Canned Soft Drink,[Sprite],$3.75

In [223]:
df.loc[df['quantity']==3].head().reset_index(drop=True)

,order_id,quantity,item_name,choice_description,item_price
0,178,3,Chicken Bowl,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$32.94
1,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20
2,284,3,Canned Soft Drink,[Diet Coke],$3.75
3,338,3,Bottled Water,NaN,$3.27
4,350,3,Canned Soft Drink,[Sprite],$3.75

In [224]:
# quantity , item_price 두개의 컬럼으로 구성된 새로운 데이터 프레임 정의
df2 = df[['quantity', 'item_price']]
df2

      quantity item_price
0            1     $2.39
1            1     $3.39
2            1     $3.39
3            1     $2.39
4            2    $16.98
...        ...        ...
4617         1    $11.75
4618         1    $11.75
4619         1    $11.25
4620         1     $8.75
4621         1     $8.75

[4622 rows x 2 columns]

In [225]:
# item_price 컬럼의 달러표시 문자를 제거하고 float 타입으로 저장하여 new_price 컬럼에 저장
df['new_price'] = df2['item_price'].str[1:].astype('float')
df

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
1,1,1,Izze,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [226]:
# new_price 컬럼이 5이하의 값을 가지는 데이터프레임을 추출하고, 전체 갯수
df3 = df.loc[df['new_price']<=5]
len(df3)

1652

In [227]:
# item_name명이 Chicken Salad Bowl 인 데이터 프레임을 추출하라고 index 값을 초기화
df4 = df.loc[df['item_name'] == 'Chicken Salad Bowl'].reset_index(drop=True)
df4

,order_id,quantity,item_name,choice_description,item_price,new_price
0,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
1,60,2,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Sour Cream, Che...",$22.50,22.50
2,94,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$22.50,22.50
3,111,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
4,137,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, Fajita Vegetables]",$17.50,17.50
...,...,...,...,...,...,...
105,1813,2,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$17.50,17.50
106,1822,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Gua...",$11.25,11.25
107,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
108,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
109,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [228]:
# new_price값이 9 이하이고 item_name 값이 Chicken Salad Bowl 인 데이터 프레임을 추출하라
df5 = df.loc[(df['new_price']<=9)&(df['item_name']=='Chicken Salad Bowl')].head()
df5

,order_id,quantity,item_name,choice_description,item_price,new_price
44,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
256,111,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$8.75,8.75
526,220,1,Chicken Salad Bowl,"[Roasted Chili Corn Salsa, [Black Beans, Sour ...",$8.75,8.75
528,221,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75
529,221,1,Chicken Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",$8.75,8.75

In [229]:
# df의 new_price 컬럼 값에 따라 오름차순으로 정리하고 index를 초기화 하여라
df.sort_values('new_price', ascending=True).reset_index(drop=True)

,order_id,quantity,item_name,choice_description,item_price,new_price
0,17,1,Bottled Water,NaN,$1.09,1.09
1,24,1,Canned Soda,[Sprite],$1.09,1.09
2,388,1,Bottled Water,NaN,$1.09,1.09
3,496,1,Canned Soda,[Diet Coke],$1.09,1.09
4,496,1,Canned Soda,[Diet Dr. Pepper],$1.09,1.09
...,...,...,...,...,...,...
4617,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$33.75,33.75
4618,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$35.00,35.00
4619,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$35.00,35.00
4620,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$35.25,35.25
4621,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25,44.25

In [230]:
# df의 item_name 컬럼 값중 Chips 포함하는 경우의 데이터를 출력하라
df.loc[df['item_name'].str.contains('Chips')]

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
6,3,1,Side of Chips,NaN,$1.69,1.69
10,5,1,Chips and Guacamole,NaN,$4.45,4.45
14,7,1,Chips and Guacamole,NaN,$4.45,4.45
...,...,...,...,...,...,...
4596,1826,1,Chips and Guacamole,NaN,$4.45,4.45
4600,1827,1,Chips and Guacamole,NaN,$4.45,4.45
4605,1828,1,Chips and Guacamole,NaN,$4.45,4.45
4613,1831,1,Chips,NaN,$2.15,2.15
4616,1832,1,Chips and Guacamole,NaN,$4.45,4.45

In [231]:
# 짝수번째 컬럼만들 포함하는 데이터 프레임 출력
df.iloc[:,::2]

      order_id                              item_name item_price
0            1           Chips and Fresh Tomato Salsa     $2.39
1            1                                   Izze     $3.39
2            1                       Nantucket Nectar     $3.39
3            1  Chips and Tomatillo-Green Chili Salsa     $2.39
4            2                           Chicken Bowl    $16.98
...        ...                                    ...        ...
4617      1833                          Steak Burrito    $11.75
4618      1833                          Steak Burrito    $11.75
4619      1834                     Chicken Salad Bowl    $11.25
4620      1834                     Chicken Salad Bowl     $8.75
4621      1834                     Chicken Salad Bowl     $8.75

[4622 rows x 3 columns]

In [232]:
# df의 new_price 컬럼 값에 따라 내림차순으로 정리하고 index를 초기화
df.sort_values('new_price', ascending=False).reset_index(drop=True)

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1443,15,Chips and Fresh Tomato Salsa,NaN,$44.25,44.25
1,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$35.25,35.25
2,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$35.00,35.00
3,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$35.00,35.00
4,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$33.75,33.75
...,...,...,...,...,...,...
4617,435,1,Canned Soda,[Mountain Dew],$1.09,1.09
4618,51,1,Canned Soda,[Diet Dr. Pepper],$1.09,1.09
4619,1014,1,Canned Soda,[Coca Cola],$1.09,1.09
4620,1009,1,Canned Soda,[Diet Coke],$1.09,1.09
4621,1009,1,Bottled Water,NaN,$1.09,1.09

In [233]:
# df의 item_name 컬럼 값이 Steak Salad 또는 Bowl 인 데이터를 인덱스
df.loc[(df['item_name'] == 'Steak Salad') | (df['item_name'] == 'Bowl')]

,order_id,quantity,item_name,choice_description,item_price,new_price
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20,22.20
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
673,279,1,Bowl,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",$7.40,7.40
752,311,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
893,369,1,Steak Salad,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$8.99,8.99
3502,1406,1,Steak Salad,"[[Lettuce, Fajita Veggies]]",$8.69,8.69

In [234]:
# df의 item_name 컬럼 값이 Steak Salad 또는 Bowl 인 데이터를 데이터 프레임화 한 후
# item_name를 기준으로 중복행이 있으면 제거하되 첫번째 케이스만 남겨라

df6 = df.loc[(df['item_name']=='Steak Salad') | (df['item_name']=='Bowl')]
df6.drop_duplicates('item_name')

,order_id,quantity,item_name,choice_description,item_price,new_price
445,193,3,Bowl,"[Braised Carnitas, Pinto Beans, [Sour Cream, C...",$22.20,22.20
664,276,1,Steak Salad,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99

In [235]:
# df의 item_name 컬럼 값이 Steak Salad 또는 Bowl 인 데이터를 데이터 프레임화 한 후
# item_name를 기준으로 중복행이 있으면 제거하되 마지막 케이스만 남겨라

df7 = df.loc[(df['item_name']=='Steak Salad') | (df['item_name']=='Bowl')]
df7.drop_duplicates('item_name', keep='last')

,order_id,quantity,item_name,choice_description,item_price,new_price
673,279,1,Bowl,"[Adobo-Marinated and Grilled Steak, [Sour Crea...",$7.40,7.40
3502,1406,1,Steak Salad,"[[Lettuce, Fajita Veggies]]",$8.69,8.69

In [236]:
# df 데이터 중 new_price 값이 new_price 값의 평균값 이상을 가지는 데이터를 인덱싱
df.loc[df['new_price'] >= df['new_price'].mean()]

,order_id,quantity,item_name,choice_description,item_price,new_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98,10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25,9.25
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [237]:
df.loc[df['item_name']=='Izze', 'item_name']='Fizzy Lizzy'
df

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
1,1,1,Fizzy Lizzy,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [238]:
df['choice_description'].isna().sum()

np.int64(1246)

In [239]:
# df의 데이터 중 choice_description 값이 NaN 인 데이터를 NoData 값으로 대체
df['choice_description'] = df['choice_description'].fillna('NoData')

In [240]:
df.loc[df['choice_description'].isnull(), 'choice_description'] == 'NoData'

df

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NoData,$2.39,2.39
1,1,1,Fizzy Lizzy,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NoData,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [241]:
# df의 데이터 중 choice_description 값에 Black이 들어가는 경우를 인덱싱
df[df['choice_description'].str.contains('Black')]

,order_id,quantity,item_name,choice_description,item_price,new_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75,11.75
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25,9.25
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75,8.75
...,...,...,...,...,...,...
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75,8.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25,11.25
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25,11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25,9.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75

In [242]:
len(df[~df['choice_description'].str.contains('Vegetables')])

3900

In [243]:
df[df['item_name'].str.startswith('N')]

,order_id,quantity,item_name,choice_description,item_price,new_price
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
105,46,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
173,77,1,Nantucket Nectar,[Apple],$3.39,3.39
205,91,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
436,189,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
601,247,2,Nantucket Nectar,[Pineapple Orange Banana],$6.78,6.78
925,381,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
1356,553,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
1585,641,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
1626,656,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
1706,690,1,Nantucket Nectar,[Apple],$3.39,3.39
2162,872,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
2379,947,2,Nantucket Nectar,[Peach Orange],$6.78,6.78
2381,947,1,Nantucket Nectar,[Apple],$3.39,3.39
2430,965,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
2653,1053,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
2818,1118,1,Nantucket Nectar,[Apple],$3.39,3.39
2838,1128,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
2853,1133,1,Nantucket Nectar,[Apple],$3.39,3.39
2949,1172,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
3318,1330,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
3368,1351,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
3570,1433,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
3845,1541,1,Nantucket Nectar,[Peach Orange],$3.39,3.39
4019,1609,1,Nantucket Nectar,[Pineapple Orange Banana],$3.39,3.39
4078,1632,1,Nantucket Nectar,[Peach Orange],$3.39,3.39

In [244]:
df[df['item_name'].str.len() >= 15]

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NoData,$2.39,2.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NoData,$2.39,2.39
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25,9.25
10,5,1,Chips and Guacamole,NoData,$4.45,4.45
...,...,...,...,...,...,...
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75,8.75
4616,1832,1,Chips and Guacamole,NoData,$4.45,4.45
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75

In [245]:
lst = [1.69, 2.39, 3.39, 4.45, 9.25, 10.98, 11.75, 16.98]
df8 = df.loc[df['new_price'].isin(lst)]

In [246]:
df8

,order_id,quantity,item_name,choice_description,item_price,new_price
0,1,1,Chips and Fresh Tomato Salsa,NoData,$2.39,2.39
1,1,1,Fizzy Lizzy,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NoData,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
...,...,...,...,...,...,...
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25,9.25
4616,1832,1,Chips and Guacamole,NoData,$4.45,4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75

In [247]:
len(df8)

1393

# Preprocess 3 : Grouping

In [248]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/AB_NYC_2019.csv')
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [249]:
df.groupby('host_name').size()

host_name
'Cil                        1
(Ari) HENRY LEE             1
(Email hidden by Airbnb)    6
(Mary) Haiy                 1
-TheQueensCornerLot         1
                           ..
단비                          1
빈나                          1
소정                          2
진                           1
현선                          1
Length: 11452, dtype: int64

In [250]:
df.groupby('host_name').size().sort_values(ascending=False).to_frame().rename(columns={0:'counts'})

              counts
host_name
Michael          417
David            403
Sonder (NYC)     327
John             294
Alex             279
...              ...
诗月                 1
辣辣                 1
思铨                 1
文清                 1
文立                 1

[11452 rows x 1 columns]

In [251]:
df.groupby(['neighbourhood_group', 'neighbourhood'], as_index=False).size()

    neighbourhood_group  neighbourhood  size
0                 Bronx       Allerton    42
1                 Bronx     Baychester     7
2                 Bronx        Belmont    24
3                 Bronx      Bronxdale    19
4                 Bronx    Castle Hill     9
..                  ...            ...   ...
216       Staten Island    Tottenville     7
217       Staten Island  West Brighton    18
218       Staten Island    Westerleigh     2
219       Staten Island    Willowbrook     1
220       Staten Island        Woodrow     1

[221 rows x 3 columns]

In [252]:
df2 = df.groupby(['neighbourhood_group', 'neighbourhood'], as_index=False).size()
df2.groupby(['neighbourhood_group'], as_index=False).max()

  neighbourhood_group    neighbourhood  size
0               Bronx         Woodlawn    70
1            Brooklyn  Windsor Terrace  3920
2           Manhattan     West Village  2658
3              Queens         Woodside   900
4       Staten Island          Woodrow    48

In [253]:
# neighbourhood_group 값에 따른 price값의 평균, 분산, 최대, 최소 값
df3 = df[['neighbourhood_group', 'price']].groupby('neighbourhood_group').agg(['mean', 'var', 'max', 'min'])
df3

                          price
                           mean           var    max min
neighbourhood_group
Bronx                 87.496792  11386.885081   2500   0
Brooklyn             124.383207  34921.719135  10000   0
Manhattan            196.875814  84904.159185  10000   0
Queens                99.517649  27923.130227  10000  10
Staten Island        114.812332  77073.088342   5000  13

In [254]:
df[['neighbourhood_group', 'reviews_per_month']].groupby('neighbourhood_group').agg(['mean', 'var', 'max', 'min'])

                    reviews_per_month
                                 mean       var    max   min
neighbourhood_group
Bronx                        1.837831  2.799878  10.34  0.02
Brooklyn                     1.283212  2.299040  14.00  0.01
Manhattan                    1.272131  2.651206  58.50  0.01
Queens                       1.941200  4.897848  20.94  0.01
Staten Island                1.872580  2.840895  10.12  0.02

In [255]:
df[['neighbourhood', 'neighbourhood_group', 'price']].groupby(['neighbourhood', 'neighbourhood_group']).agg(['mean'])

                                          price
                                           mean
neighbourhood   neighbourhood_group
Allerton        Bronx                 87.595238
Arden Heights   Staten Island         67.250000
Arrochar        Staten Island        115.000000
Arverne         Queens               171.779221
Astoria         Queens               117.187778
...                                         ...
Windsor Terrace Brooklyn             138.993631
Woodhaven       Queens                67.170455
Woodlawn        Bronx                 60.090909
Woodrow         Staten Island        700.000000
Woodside        Queens                85.097872

[221 rows x 1 columns]

In [256]:
# neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 계층적 indexing 없이 구하라

df4 = df[['neighbourhood', 'neighbourhood_group', 'price']].groupby(['neighbourhood', 'neighbourhood_group']).mean().unstack()
df4

                         price
neighbourhood_group      Bronx    Brooklyn Manhattan      Queens Staten Island
neighbourhood
Allerton             87.595238         NaN       NaN         NaN           NaN
Arden Heights              NaN         NaN       NaN         NaN         67.25
Arrochar                   NaN         NaN       NaN         NaN        115.00
Arverne                    NaN         NaN       NaN  171.779221           NaN
Astoria                    NaN         NaN       NaN  117.187778           NaN
...                        ...         ...       ...         ...           ...
Windsor Terrace            NaN  138.993631       NaN         NaN           NaN
Woodhaven                  NaN         NaN       NaN   67.170455           NaN
Woodlawn             60.090909         NaN       NaN         NaN           NaN
Woodrow                    NaN         NaN       NaN         NaN        700.00
Woodside                   NaN         NaN       NaN   85.097872           NaN

[221 rows x 5 columns]

In [257]:
# neighbourhood 값과 neighbourhood_group 값에 따른 price 의 평균을 계층적 indexing 없이 구하고 nan 값은 -999값으로 채워라

df[['neighbourhood', 'neighbourhood_group', 'price']].groupby(['neighbourhood', 'neighbourhood_group']).mean().unstack().fillna(-999)

                          price                                    \
neighbourhood_group       Bronx    Brooklyn Manhattan      Queens
neighbourhood
Allerton              87.595238 -999.000000    -999.0 -999.000000
Arden Heights       -999.000000 -999.000000    -999.0 -999.000000
Arrochar            -999.000000 -999.000000    -999.0 -999.000000
Arverne             -999.000000 -999.000000    -999.0  171.779221
Astoria             -999.000000 -999.000000    -999.0  117.187778
...                         ...         ...       ...         ...
Windsor Terrace     -999.000000  138.993631    -999.0 -999.000000
Woodhaven           -999.000000 -999.000000    -999.0   67.170455
Woodlawn              60.090909 -999.000000    -999.0 -999.000000
Woodrow             -999.000000 -999.000000    -999.0 -999.000000
Woodside            -999.000000 -999.000000    -999.0   85.097872


neighbourhood_group Staten Island
neighbourhood
Allerton                  -999.00
Arden Heights               67.25
Arrochar                   115.00
Arverne                   -999.00
Astoria                   -999.00
...                           ...
Windsor Terrace           -999.00
Woodhaven                 -999.00
Woodlawn                  -999.00
Woodrow                    700.00
Woodside                  -999.00

[221 rows x 5 columns]

In [258]:
# 데이터중 neighbourhood_group 값이 Queens값을 가지는 데이터들 중 neighbourhood 그룹별로 price값의 평균, 분산, 최대, 최소값
df.loc[df['neighbourhood_group'] == 'Queens'].groupby('neighbourhood').price.agg(['mean', 'var', 'max', 'min'])

                           mean            var    max  min
neighbourhood
Arverne              171.779221   37383.411141   1500   35
Astoria              117.187778  122428.811196  10000   25
Bay Terrace          142.000000    6816.400000    258   32
Bayside              157.948718  166106.470985   2600   30
Bayswater             87.470588    2330.889706    230   45
Belle Harbor         171.500000    8226.571429    350   85
Bellerose             99.357143    3093.016484    240   42
Breezy Point         213.333333    1008.333333    250  195
Briarwood            105.875000   18503.165909   1000   30
Cambria Heights       81.730769    2960.604615    250   31
College Point         88.000000    6445.555556    400   44
Corona                59.171875    2430.557292    359   23
Ditmars Steinway      95.029126    4214.112785    600   22
Douglaston            82.750000    2347.071429    178   40
East Elmhurst         81.183784    4369.487779    700   16
Edgemere              94.727273    4219.418182    200   40
Elmhurst              80.459916    3896.563005    443   15
Far Rockaway         165.862069   52575.980296    900   35
Flushing              93.514085   12417.177448   1500   15
Forest Hills         121.625000   44533.368881   2350   16
Fresh Meadows         99.500000    6394.451613    375   39
Glendale              90.796296    3230.882250    299   25
Hollis                88.642857    1483.016484    175   50
Holliswood           135.750000    5091.583333    239   79
Howard Beach         115.400000    4241.936842    250   40
Jackson Heights       80.897849    2150.470590    260   23
Jamaica               95.770563    8067.047130   1000   10
Jamaica Estates      182.947368   29006.052632    750   35
Jamaica Hills        132.125000   11304.696429    325   50
Kew Gardens           88.375000    2632.306452    219   35
Kew Gardens Hills    112.307692    6230.621538    399   40
Laurelton             95.333333    4355.529412    254   34
Little Neck           75.200000    2368.700000    149   32
Long Island City     127.465549   15529.503009   2000   30
Maspeth               83.645455    2223.607089    245   11
Middle Village       109.580645    3537.118280    265   28
Neponsit             274.666667    5625.333333    350  200
Ozone Park            85.274194    1705.415389    200   25
Queens Village        83.933333    2386.470056    320   25
Rego Park             83.877358    3659.003863    300   21
Richmond Hill         87.117021    3474.147449    300   28
Ridgewood             77.184397    2629.311889    375   20
Rockaway Beach       132.178571    6254.622078    545   49
Rosedale              76.694915    2963.939801    350   22
South Ozone Park      82.400000    4619.989744    400   29
Springfield Gardens   94.235294    2490.848739    300   40
St. Albans           100.828947    9489.903684    600   25
Sunnyside             84.865014    2727.746922    600   12
Whitestone           107.545455   13632.072727    400   35
Woodhaven             67.170455    1642.464864    250   10
Woodside              85.097872    5001.900636    500   28

In [259]:
# 데이터중 neighbourhood_group 값에 따른 room_type 컬럼의 숫자를 구하고 neighbourhood_group 값을 기준으로 각 값의 비율
df3 = df[['neighbourhood_group','room_type']].groupby(['neighbourhood_group','room_type']).size().unstack()
df3.loc[:,:] = (df3.values /df3.sum(axis=1).values.reshape(-1,1))
df3

<ipython-input-259-1474273872>:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.34738772 0.47547752 0.60934398 0.36992587 0.47184987]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df3.loc[:,:] = (df3.values /df3.sum(axis=1).values.reshape(-1,1))
<ipython-input-259-1474273872>:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.59761687 0.50397931 0.36849638 0.59512884 0.50402145]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df3.loc[:,:] = (df3.values /df3.sum(axis=1).values.reshape(-1,1))
<ipython-input-259-1474273872>:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.05499542 0.02054318 0.02215964 0.03494529 0.02412869]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df3.loc[:,:] = (df3.values /df3.sum(axis=1).values.reshape(-1,1))

room_type            Entire home/apt  Private room  Shared room
neighbourhood_group
Bronx                       0.347388      0.597617     0.054995
Brooklyn                    0.475478      0.503979     0.020543
Manhattan                   0.609344      0.368496     0.022160
Queens                      0.369926      0.595129     0.034945
Staten Island               0.471850      0.504021     0.024129

# Preprocessing 4 : Apply, Map

In [260]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/BankChurnersUp.csv', index_col=0)
df

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,3,2,3,4003.0,1851,2152.0,0.703,15476
10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764
10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,5,3,4,5409.0,0,5409.0,0.819,10291
10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,4,3,3,5281.0,0,5281.0,0.535,8395
10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294

In [261]:
df.shape

(10127, 18)

Income_Category의 카테고리를 map 함수를 이용하여 다음과 같이 변경하여 newIncome 컬럼에 매핑하라

Unknown : N

Less than $40K : a

$40K - $60K : b

$60K - $80K : c

$80K - $120K : d

$120K +’ : e

In [262]:
dic = {
    'Unknown' : 'N',
    'Less than $40K' : 'a',
    '$40K - $60K' : 'b',
    '$60K - $80K' : 'c',
    '$80K - $120K' : 'd',
    '$120K +' : 'e'
}

df['newIncome'] = df['Income_Category'].map(lambda x: dic[x])
df['newIncome']

0        c
1        a
2        d
3        a
4        c
        ..
10122    b
10123    b
10124    a
10125    b
10126    a
Name: newIncome, Length: 10127, dtype: object

In [263]:
# Apply 를 사용해서 매핑하라 (Apply : 함수 적용)

def category(x):
  if x == 'Unknown':
    return 'N'
  elif x == 'Less than $40K' :
    return 'a'
  elif x == '$40K - $60K' :
    return 'b'
  elif x == '$60K - $80K' :
    return 'c'
  elif x == '$80K - $120K' :
    return 'd'
  elif x == '$120K+' :
    return 'e'

df['newIncome'] = df['Income_Category'].apply(category)
df['newIncome']

0        c
1        a
2        d
3        a
4        c
        ..
10122    b
10123    b
10124    a
10125    b
10126    a
Name: newIncome, Length: 10127, dtype: object

In [264]:
# Customer_Age의 값을 이용하여 나이 구간을 AgeState 컬럼으로 정의하라.

def rounddown(x):
   return (x // 10) * 10

df['AgeState'] = df['Customer_Age'].apply(rounddown)

# df['AgeState'] = df['Customer_Age'].map(lambda x: x//10 * 10)

df['AgeState'].value_counts().sort_index()

AgeState
20     195
30    1841
40    4561
50    2998
60     530
70       2
Name: count, dtype: int64

In [265]:
df['newEduLevel'] = df['Education_Level'].map(lambda x : 1 if 'Graduate' in x else 0)
df['newEduLevel'].value_counts()

newEduLevel
0    6483
1    3644
Name: count, dtype: int64

In [266]:
# Credit_Limit 컬럼값이 4500 이상인 경우 1 그외의 경우에는 모두 0으로 하는 newLimit 정의하라.
# newLimit 각 값들의 빈도수를 출력하라

df['newLimit'] = df['Credit_Limit'].map(lambda x: 1 if x>=4500 else 0)
df['newLimit'].value_counts()

newLimit
1    5096
0    5031
Name: count, dtype: int64

In [267]:
# Marital_Status 컬럼값이 Married 이고 Card_Category 컬럼의 값이 Platinum인 경우 1 그외의 경우에는 모두 0으로 하는 newState컬럼을 정의하라.
# newState의 각 값들의 빈도수를 출력하라

def category2(x):
  if x['Marital_Status'] == 'Married' and x['Card_Category'] == 'Platinum':
    return 1
  else :
    return 0

df['newState'] = df.apply(category2, axis=1)
df['newState'].value_counts()

newState
0    10120
1        7
Name: count, dtype: int64

In [268]:
# Gender 컬럼값 M인 경우 male F인 경우 female로 값을 변경하여 Gender 컬럼에 새롭게 정의하라.
# 각 value의 빈도를 출력하라

def changegender(x):
  if x=='M' :
    return 'male'
  elif x=='F' :
    return 'female'

df['Gender'] = df['Gender'].apply(changegender)
df['Gender'].value_counts()

Gender
female    5358
male      4769
Name: count, dtype: int64

# Preprocessing 5 : Time_Series

In [269]:
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/timeTest.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6574 entries, 0 to 6573
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Yr_Mo_Dy  6574 non-null   object
 1   RPT       6568 non-null   float64
 2   VAL       6571 non-null   float64
 3   ROS       6572 non-null   float64
 4   KIL       6569 non-null   float64
 5   SHA       6572 non-null   float64
 6   BIR       6574 non-null   float64
 7   DUB       6571 non-null   float64
 8   CLA       6572 non-null   float64
 9   MUL       6571 non-null   float64
 10  CLO       6573 non-null   float64
 11  BEL       6574 non-null   float64
 12  MAL       6570 non-null   float64
dtypes: float64(12), object(1)
memory usage: 667.8+ KB

In [270]:
df['Yr_Mo_Dy'] = pd.to_datetime(df['Yr_Mo_Dy'])
df['Yr_Mo_Dy']

0      2061-01-01
1      2061-01-02
2      2061-01-03
3      2061-01-04
4      2061-01-05
          ...
6569   1978-12-27
6570   1978-12-28
6571   1978-12-29
6572   1978-12-30
6573   1978-12-31
Name: Yr_Mo_Dy, Length: 6574, dtype: datetime64[ns]

In [271]:
# Yr_Mo_Dy에 존재하는 년도의 유일값을 모두 출력하라
df['Yr_Mo_Dy'].dt.year.unique()

array([2061, 2062, 2063, 2064, 2065, 2066, 2067, 2068, 2069, 2070, 1971,
       1972, 1973, 1974, 1975, 1976, 1977, 1978], dtype=int32)

In [272]:
# Yr_Mo_Dy에 년도가 2061년 이상의 경우에는 모두 잘못된 데이터이다.
# 해당경우의 값은 100을 빼서 새롭게 날짜를 Yr_Mo_Dy 컬럼에 정의하라.

def fix_centry(x):
  import datetime

  year = x.year - 100 if x.year >=2061 else x.year
  return pd.to_datetime(datetime.date(year, x.month, x.day))

df['Yr_Mo_Dy'] = df['Yr_Mo_Dy'].apply(fix_centry)
df['Yr_Mo_Dy']

0      1961-01-01
1      1961-01-02
2      1961-01-03
3      1961-01-04
4      1961-01-05
          ...
6569   1978-12-27
6570   1978-12-28
6571   1978-12-29
6572   1978-12-30
6573   1978-12-31
Name: Yr_Mo_Dy, Length: 6574, dtype: datetime64[ns]

In [273]:
def changeyear(x):
  import datetime
  new_year = x.year - 100 if x.year >= 2061 else x.year
  return pd.to_datetime(datetime.date(new_year, x.month, x.day))

df['Yr_Mo_Dy'] = df['Yr_Mo_Dy'].apply(changeyear)
df['Yr_Mo_Dy']

0      1961-01-01
1      1961-01-02
2      1961-01-03
3      1961-01-04
4      1961-01-05
          ...
6569   1978-12-27
6570   1978-12-28
6571   1978-12-29
6572   1978-12-30
6573   1978-12-31
Name: Yr_Mo_Dy, Length: 6574, dtype: datetime64[ns]

In [280]:
# 년도별 각 컬럼의 평균값


df.iloc[:,1:].groupby(df.Yr_Mo_Dy.dt.year).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Yr_Mo_Dy,,,,,,,,,,,,
1961,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

In [282]:
df['weekday'] = df['Yr_Mo_Dy'].dt.weekday
df['weekday']

0       6
1       0
2       1
3       2
4       3
       ..
6569    2
6570    3
6571    4
6572    5
6573    6
Name: weekday, Length: 6574, dtype: int32

In [287]:
df['WeekCheck'] = df['weekday'].map(lambda x: 1 if x>=5 else 0)
df['WeekCheck']

0       1
1       0
2       0
3       0
4       0
       ..
6569    0
6570    0
6571    0
6572    1
6573    1
Name: WeekCheck, Length: 6574, dtype: int64

In [292]:
# 년도, 일자 상관없이 모든 컬럼의 각 달의 평균을 구하여라
df.iloc[:,1:].groupby(df['Yr_Mo_Dy'].dt.month).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,weekday,WeekCheck
Yr_Mo_Dy,,,,,,,,,,,,,,
1,14.847325,12.914560,13.299624,7.199498,11.667734,8.054839,11.819355,9.512047,9.543208,10.053566,14.550520,18.028763,2.989247,0.284946
2,13.710906,12.111122,12.879132,6.942411,11.551772,7.633858,11.206024,9.341437,9.313169,9.518051,13.728898,17.156142,3.005906,0.287402
3,13.158687,11.505842,12.648118,7.265907,11.554516,7.959409,11.310179,9.635896,9.700324,10.096953,13.810609,16.909317,3.000000,0.283154
4,12.555648,10.429759,12.204815,6.898037,10.677667,7.441389,10.221315,8.909056,8.930870,9.158019,12.664759,14.937611,3.011111,0.288889
5,11.724032,10.145619,11.550394,6.307487,10.224301,6.942061,8.797738,8.452903,8.040806,8.524857,12.767258,13.736039,2.982079,0.283154
6,10.451317,8.949704,10.361315,5.652278,9.529926,6.410093,8.009556,7.920796,7.639796,7.729185,12.246407,12.861818,3.007407,0.285185
7,9.992007,8.357778,9.349642,5.416935,9.302634,5.972348,7.843501,7.262760,7.544480,7.321416,11.676505,12.800789,3.001792,0.288530
8,10.213411,8.415143,9.993441,5.270681,8.901559,5.891057,7.772312,6.842025,7.240573,7.002783,11.110090,12.565943,2.991039,0.283154
9,11.458519,9.981002,10.756883,5.615176,9.766315,6.566222,8.609722,7.745677,7.610556,7.689278,12.686389,14.761963,3.009259,0.287037
10,12.660610,11.010681,11.453943,6.065215,10.550251,7.159910,9.387778,8.726308,8.347181,8.850376,14.155323,16.697151,2.998208,0.286738
11,13.200722,11.639500,12.293407,6.247611,10.501130,7.134333,10.814861,8.427167,8.604000,8.943167,13.815741,18.114185,2.992593,0.283333
12,14.446398,12.353602,13.212276,6.829910,11.301254,7.963710,11.849050,9.209355,9.447258,9.627670,14.259516,18.697599,3.017921,0.288530

In [297]:
# 모든 결측치는 컬럼기준 직전의 값으로 대체하고 첫번째 행에 결측치가 있을경우 뒤에있는 값으로 대채하라
df = df.fillna(method='ffill').fillna(method='bfill')
df.isna().sum()

<ipython-input-297-957645041>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill').fillna(method='bfill')

Yr_Mo_Dy     0
RPT          0
VAL          0
ROS          0
KIL          0
SHA          0
BIR          0
DUB          0
CLA          0
MUL          0
CLO          0
BEL          0
MAL          0
weekday      0
WeekCheck    0
dtype: int64

In [305]:
df.iloc[:,1:].groupby(df['Yr_Mo_Dy'].dt.to_period('M')).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,weekday,WeekCheck
Yr_Mo_Dy,,,,,,,,,,,,,,
1961-01,14.932581,12.084194,13.431613,7.736774,11.215806,8.588065,11.184839,9.270968,9.085806,10.107419,13.880968,14.703226,2.935484,0.290323
1961-02,16.269286,14.975357,14.324643,9.116786,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786,3.000000,0.285714
1961-03,11.015806,11.296452,10.752903,7.137742,10.509355,8.866774,9.644194,9.829677,10.646129,11.251935,16.410968,15.637742,3.000000,0.258065
1961-04,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333,3.166667,0.333333
1961-05,9.860968,8.735161,10.818065,5.892258,9.490323,6.574839,7.477097,8.177097,8.039355,8.499355,11.900323,12.011613,2.806452,0.258065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194,2.903226,0.258065
1978-09,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333,3.100000,0.300000
1978-10,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000,2.935484,0.290323
1978-11,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000,2.966667,0.266667
1978-12,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613,3.193548,0.322581

In [307]:
# RPT 컬럼의 값을 일자별 기준으로 1차차분하라
df['RPT'].diff()

0        NaN
1      -0.33
2       3.79
3      -7.92
4       2.75
        ...
6569    3.75
6570   -4.37
6571    0.79
6572    4.50
6573    1.83
Name: RPT, Length: 6574, dtype: float64

In [308]:
df[['RPT', 'VAL']].rolling(7).mean()

            RPT        VAL
0           NaN        NaN
1           NaN        NaN
2           NaN        NaN
3           NaN        NaN
4           NaN        NaN
...         ...        ...
6569  11.868571   9.362857
6570  11.904286   9.595714
6571  13.017143  10.011429
6572  13.285714  10.118571
6573  14.951429  11.801429

[6574 rows x 2 columns]

In [327]:
df =pd.read_csv('https://raw.githubusercontent.com/Datamanim/pandas/main/seoul_pm.csv')
df.head()

,(년-월-일:시),PM10등급,PM10,PM2.5등급,PM2.5,오존등급,오존,이산화질소등급,이산화질소,일산화탄소등급,일산화탄소,아황산가스등급,아황산가스
0,2021-05-15:15,보통,47.0,보통,19.0,좋음,0.017,좋음,0.023,좋음,0.4,좋음,0.003
1,2021-05-15:14,보통,43.0,보통,20.0,좋음,0.024,좋음,0.019,좋음,0.3,좋음,0.003
2,2021-05-15:13,보통,34.0,보통,24.0,보통,0.035,좋음,0.017,좋음,0.4,좋음,0.004
3,2021-05-15:12,보통,41.0,보통,27.0,보통,0.037,좋음,0.020,좋음,0.4,좋음,0.004
4,2021-05-15:11,보통,51.0,보통,34.0,보통,0.033,좋음,0.023,좋음,0.4,좋음,0.005

In [328]:
# 년-월-일:시 컬럼을 pandas에서 인식할 수 있는 datetime 형태로 변경하라.
# 서울시의 제공데이터의 경우 0시가 24시로 표현된다

def change_date(x):
  import datetime
  hour = x.split(':')[1]
  date = x.split(':')[0]

  if hour == '24':
    hour = '00:00:00'

    FinalDate = pd.to_datetime(date+' '+hour) + datetime.timedelta(days=1)
  else:
    hour = hour + ':00:00'
    FinalDate = pd.to_datetime(date+' '+hour)

  return FinalDate

df['(년-월-일:시)'] = df['(년-월-일:시)'].apply(change_date)
df['(년-월-일:시)']

0      2021-05-15 15:00:00
1      2021-05-15 14:00:00
2      2021-05-15 13:00:00
3      2021-05-15 12:00:00
4      2021-05-15 11:00:00
               ...
1234   2021-03-25 05:00:00
1235   2021-03-25 04:00:00
1236   2021-03-25 03:00:00
1237   2021-03-25 02:00:00
1238   2021-03-25 01:00:00
Name: (년-월-일:시), Length: 1239, dtype: datetime64[ns]

In [335]:
df['dayName'] = df['(년-월-일:시)'].dt.day_name()
df['dayName']

0       Saturday
1       Saturday
2       Saturday
3       Saturday
4       Saturday
          ...
1234    Thursday
1235    Thursday
1236    Thursday
1237    Thursday
1238    Thursday
Name: dayName, Length: 1239, dtype: object

In [350]:
df2 = df.groupby(['dayName','PM10등급'],as_index=False).size()
df2.pivot(index='dayName', columns='PM10등급', values='size')

PM10등급       나쁨  매우나쁨     보통    좋음
dayName
Friday     31.0  17.0  120.0  21.0
Monday      1.0  21.0   83.0  63.0
Saturday   31.0  27.0   71.0  54.0
Sunday      2.0   1.0   67.0  98.0
Thursday   41.0   NaN  144.0   5.0
Tuesday    13.0  10.0   71.0  74.0
Wednesday  26.0   NaN   95.0  46.0

In [352]:
check = len(df['(년-월-일:시)'].diff().unique())
if check == 2:
  Ans = True
else:
  Ans = False

Ans

True